const task = [
     {
          _id: '1',
          status: 'Proposed',
          data: 'Mon, jun 12',
          text: 'Retro occupy organic, stumptown shabby',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '2',
          status: 'Proposed',
          data: 'Mon, jun 12',
          text: 'Retro occupy organic',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '3',
          status: 'Proposed',
          data: 'Mon, jun 12',
          text: 'By So Delight Of Showing Neither Believe He Present. Deal Sigh Up In Shew Away When.',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '4',
          status: 'In Progress',
          data: 'Mon, jun 12',
          text: 'Kogi Cosby sweater ethical squid irony disrupt.',
          img: 'image1',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '5',
          status: 'In Progress',
          data: 'Mon, jun 12',
          text: 'Retro occupy organic',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '6',
          status: 'Review',
          data: 'Mon, jun 12',
          text: 'Retro occupy organic, stumptown shabby',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '7',
          status: 'Review',
          data: 'Mon, jun 12',
          text: 'By So Delight Of Showing Neither Believe He Present. Deal Sigh Up In Shew Away When.',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '8',
          status: 'Complete',
          data: 'Mon, jun 12',
          text: 'Kogi Cosby sweater ethical squid irony disrupt.',
          img: 'image2',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
     {
          _id: '8',
          status: 'Complete',
          data: 'Mon, jun 12',
          text: 'Retro occupy organic',
          img: '',
          icon: '',
          see: '3',
          comment: '12',
          save: '7',
     },
]

export default task
